# Reference: http://mirror.jmu.edu/pub/CTAN/macros/latex/contrib/unicode-math/unicode-math-usv.dtx
#
# TODO:
#   - Dotless Variants?
#   - Variable Greeks? `\varepsilon` etc.
#   - Variants of operators, paranthesis, etc.

# This information is used in two places:
#    For font selection: Unicode -> Font Selection -> Unicode
#    Exceptions are used in Unicode -> { Font Dimensions, Unicode Redirect }

#undefined="0x29C4"

[Latin]
normal="0x1D434"        #rm_it
normal_it="0x1D434"     #rm_it
normal_bf="0x1D400"     #rm_bf
normal_bfit="0x1D468"   #rm_bfit
rm="65"
rm_it="0x1D434"
rm_bf="0x1D400"
rm_bfit="0x1D468"
bb="0x1D538"
scr="0x1D49C"
scr_bf="0x1D4D0"
cal="0x1D49C"
cal_bf="0x1D4D0"   # These should probably not be the same, need a fallback
frak="0x1D504"
frak_bf="0x1D56C"
sf="0x1D5A0"
sf_it="0x1D608"
sf_bf="0x1D5D4"
sf_bfit="0x1D63C"
tt="0x1D670"
    [Latin.exceptions]
    # Calligraphic
    "0x1D49D"="0x212C"    # B
    "0x1D4A0"="0x2130"    # E
    "0x1D4A1"="0x2131"    # F
    "0x1D4A3"="0x210B"    # H
    "0x1D4A4"="0x2110"    # I
    "0x1D4A7"="0x2112"    # L
    "0x1D4A8"="0x2133"    # M
    "0x1D4AD"="0x211B"    # R

    # Double Struck
    "0x1D53A"="0x2102"    # C
    "0x1D53F"="0x210D"    # H
    "0x1D545"="0x2115"    # N
    "0x1D547"="0x2119"    # P
    "0x1D548"="0x211A"    # Q
    "0x1D549"="0x211D"    # R
    "0x1D551"="0x2124"    # Z
    
    # Fractur
    "0x1D506"="0x212D"    # C
    "0x1D50B"="0x210C"    # H
    "0x1D50C"="0x2111"    # I
    "0x1D515"="0x211C"    # R
    "0x1D51D"="0x2128"    # Z

[latin]
normal="0x1D44E"        #rm_it
normal_it="0x1D44E"     #rm_it
normal_bf="0x1D41A"     #rm_bf
normal_bfit="0x1D482"   #rm_bfit
rm="97"
rm_it="0x1D44E"
rm_bf="0x1D41A"
rm_bfit="0x1D482"
bb="0x1D552"
scr="0x1D4B6"
scr_bf="0x1D4EA"
frak="0x1D51E"
frak_bf="0x1D586"
sf="0x1D5BA"
sf_bf="0x1D5EE"
sf_it="0x1D622"
sf_bfit="0x1D656"
tt="0x1D68A"
    [latin.exceptions]
    # Italic
    "0x1D455"="0x210E"      # h

    # Scripts
    "0x1D4BA"="0x212F"      # e
    "0x1D4BC"="0x210A"      # g
    "0x1D4C4"="0x2134"      # o

[digits]
normal="48"         #rm
normal_bf="0x1D7CE" #rm_bf
normal_it="0x1D7E2" #sf_it
normal_bfit="0x1D7CE" #rm_bf
rm="48"
rm_bf="0x1D7CE"
rm_bfit="0x1D7CE"
bb="0x1D7D8"
sf="0x1D7E2"
sf_it="0x1D7E2"
sf_bf="0x1D7CE"
sf_bfit="0x1D7CE"
tt="0x1D7F6"

[Greek]
normal="0x1D6E2"
normal_bf="0x1D6A8"
normal_it="0x1D6E2"
normal_bfit="0x1D71C" 
rm="0x391"
rm_it="0x1D6E2"
rm_bf="0x1D6A8"
rm_bfit="0x1D71C"
sf_bf="0x1D756"
sf_it="0x1D790"

[greek]
normal="0x1D6FC"
normal_bf="0x1D6C2"
normal_it="0x1D6FC"
normal_bfit="0x1D736"
rm="0x3B1"
rm_it="0x1D6FC"
rm_bf="0x1D6C2"
rm_bfit="0x1D736"
sf_bf="0x1D770"
sf_bfit="0x1D7AA"
