// DO NOT MODIFY.  This file is automatically generated by `constants.py`
// in the rex-font repo.
//
// Font: TODO\
<%! from datetime import datetime %>
// Modified: ${datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

use font_types::FontUnit;

pub const UNITS_PER_EM: FontUnit = fontunit!(${upem});
pub const MIN_CONNECTOR_OVERLAP: FontUnit = fontunit!(${connector_overlap});

% for (name, unit) in constants:
pub const ${name.upper()}: FontUnit = fontunit!(${unit});
% endfor

% for (name, unit) in percents:
pub const ${name.upper()}: FonUnit = fontunit_raw!(${hex(int(unit / 100 * 2 ** 8))}); // ${unit} %
% endfor