// DO NOT MODIFY.  This file is automatically generated by `gen_constats.py` 
// in the rex-font repo.
//
// Font: 
// Modified: 2017-07-08 11:21:32

#![allow(dead_code)]
use dimensions::FontUnit;

pub const UNITS_PER_EM: u16 = 1000;
pub const MIN_CONNECTOR_OVERLAP: u32 = 20

pub const ACCENT_BASE_HEIGHT: FontUnit<i16> = FontUnit(450);
pub const AXIS_HEIGHT: FontUnit<i16> = FontUnit(250);
pub const DELIMITED_SUB_FORMULA_MIN_HEIGHT: FontUnit<u16> = FontUnit(1300);
pub const DISPLAY_OPERATOR_MIN_HEIGHT: FontUnit<u16> = FontUnit(1300);
pub const FLATTENED_ACCENT_BASE_HEIGHT: FontUnit<i16> = FontUnit(664);
pub const FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN: FontUnit<i16> = FontUnit(120);
pub const FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN: FontUnit<i16> = FontUnit(686);
pub const FRACTION_DENOMINATOR_GAP_MIN: FontUnit<i16> = FontUnit(40);
pub const FRACTION_DENOMINATOR_SHIFT_DOWN: FontUnit<i16> = FontUnit(345);
pub const FRACTION_NUM_DISPLAY_STYLE_GAP_MIN: FontUnit<i16> = FontUnit(120);
pub const FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP: FontUnit<i16> = FontUnit(677);
pub const FRACTION_NUMERATOR_GAP_MIN: FontUnit<i16> = FontUnit(40);
pub const FRACTION_NUMERATOR_SHIFT_UP: FontUnit<i16> = FontUnit(394);
pub const FRACTION_RULE_THICKNESS: FontUnit<i16> = FontUnit(40);
pub const LOWER_LIMIT_BASELINE_DROP_MIN: FontUnit<i16> = FontUnit(600);
pub const LOWER_LIMIT_GAP_MIN: FontUnit<i16> = FontUnit(167);
pub const MATH_LEADING: FontUnit<i16> = FontUnit(154);
pub const OVERBAR_EXTRA_ASCENDER: FontUnit<i16> = FontUnit(40);
pub const OVERBAR_RULE_THICKNESS: FontUnit<i16> = FontUnit(40);
pub const OVERBAR_VERTICAL_GAP: FontUnit<i16> = FontUnit(120);
pub const RADICAL_DEGREE_BOTTOM_RAISE_PERCENT: FontUnit<i16> = FontUnit(60);
pub const RADICAL_DISPLAY_STYLE_VERTICAL_GAP: FontUnit<i16> = FontUnit(148);
pub const RADICAL_EXTRA_ASCENDER: FontUnit<i16> = FontUnit(40);
pub const RADICAL_KERN_AFTER_DEGREE: FontUnit<i16> = FontUnit(-556);
pub const RADICAL_KERN_BEFORE_DEGREE: FontUnit<i16> = FontUnit(278);
pub const RADICAL_RULE_THICKNESS: FontUnit<i16> = FontUnit(40);
pub const RADICAL_VERTICAL_GAP: FontUnit<i16> = FontUnit(50);
pub const SCRIPT_PERCENT_SCALE_DOWN: FontUnit<i16> = FontUnit(70);
pub const SCRIPT_SCRIPT_PERCENT_SCALE_DOWN: FontUnit<i16> = FontUnit(50);
pub const SKEWED_FRACTION_HORIZONTAL_GAP: FontUnit<i16> = FontUnit(350);
pub const SKEWED_FRACTION_VERTICAL_GAP: FontUnit<i16> = FontUnit(96);
pub const SPACE_AFTER_SCRIPT: FontUnit<i16> = FontUnit(56);
pub const STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN: FontUnit<i16> = FontUnit(686);
pub const STACK_BOTTOM_SHIFT_DOWN: FontUnit<i16> = FontUnit(345);
pub const STACK_DISPLAY_STYLE_GAP_MIN: FontUnit<i16> = FontUnit(280);
pub const STACK_GAP_MIN: FontUnit<i16> = FontUnit(120);
pub const STACK_TOP_DISPLAY_STYLE_SHIFT_UP: FontUnit<i16> = FontUnit(677);
pub const STACK_TOP_SHIFT_UP: FontUnit<i16> = FontUnit(444);
pub const STRETCH_STACK_BOTTOM_SHIFT_DOWN: FontUnit<i16> = FontUnit(600);
pub const STRETCH_STACK_GAP_ABOVE_MIN: FontUnit<i16> = FontUnit(200);
pub const STRETCH_STACK_GAP_BELOW_MIN: FontUnit<i16> = FontUnit(167);
pub const STRETCH_STACK_TOP_SHIFT_UP: FontUnit<i16> = FontUnit(111);
pub const SUB_SUPERSCRIPT_GAP_MIN: FontUnit<i16> = FontUnit(160);
pub const SUBSCRIPT_BASELINE_DROP_MIN: FontUnit<i16> = FontUnit(200);
pub const SUBSCRIPT_SHIFT_DOWN: FontUnit<i16> = FontUnit(247);
pub const SUBSCRIPT_TOP_MAX: FontUnit<i16> = FontUnit(344);
pub const SUPERSCRIPT_BASELINE_DROP_MAX: FontUnit<i16> = FontUnit(250);
pub const SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT: FontUnit<i16> = FontUnit(344);
pub const SUPERSCRIPT_BOTTOM_MIN: FontUnit<i16> = FontUnit(108);
pub const SUPERSCRIPT_SHIFT_UP: FontUnit<i16> = FontUnit(363);
pub const SUPERSCRIPT_SHIFT_UP_CRAMPED: FontUnit<i16> = FontUnit(289);
pub const UNDERBAR_EXTRA_DESCENDER: FontUnit<i16> = FontUnit(40);
pub const UNDERBAR_RULE_THICKNESS: FontUnit<i16> = FontUnit(40);
pub const UNDERBAR_VERTICAL_GAP: FontUnit<i16> = FontUnit(120);
pub const UPPER_LIMIT_BASELINE_RISE_MIN: FontUnit<i16> = FontUnit(111);
pub const UPPER_LIMIT_GAP_MIN: FontUnit<i16> = FontUnit(200);
