<%! from datetime import datetime %>
// DO NOT MODIFY!
//
// This file is automatically generated by the ../tools/parse-unicode-math.py file using the
// unicode-math-table.tex file taken from `unicode-math` on CTAN. If you find a bug
// in this file, please modify ../tools/parse-unicode-math.py accordingly instead.
//
// FIXME: Switch to PHF when avialable on stable.  Benchmarks shows it is slightly
//   faster with this dataset.
//
// Font: \
// Modified: ${datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

use font::{Glyph, BBox};
use static_map::Map;

pub static GLYPHS: Map<CodePoint, Glyph> = static_map! {
%for glyph in glyphs.values():
    ${'0x%04x' % glyph['usv']}_u32 => Glyph { usv: ${'0x%04x' % glyph['usv']}_u32, BBox(${glyph['xmin']}i16, ${glyph['ymin']}i16, ${glyph['xmax']}i16, ${glyph['ymax']}i16), attachment: ${glyph['attachment']}i16, advance: ${glyph['advance']}i16, lsb: ${glyph['lsb']}i16, italics: ${glyph['italics']}i16 },
%endfor
};